local test_root = vim.fn.tempname()
vim.fn.mkdir(test_root .. "/nested", "p")
local function command(args)
  local result = vim.system(args, { text = true }):wait()
  assert(result.code == 0, result.stderr)
end
command({ "git", "-C", test_root, "init", "-q" })
command({ "git", "-C", test_root, "config", "user.email", "test@example.com" })
command({ "git", "-C", test_root, "config", "user.name", "Test" })
vim.fn.writefile({ "initial" }, test_root .. "/nested/file.txt")
command({ "git", "-C", test_root, "add", "." })
command({ "git", "-C", test_root, "commit", "-qm", "initial" })
vim.fn.writefile({ "second" }, test_root .. "/second.txt")
command({ "git", "-C", test_root, "add", "." })
command({ "git", "-C", test_root, "commit", "-qm", "second" })
vim.cmd.cd(vim.fn.fnameescape(test_root))
local lazyrepo = require("views.lazyrepo")

vim.o.columns = 120
vim.o.lines = 40
lazyrepo.launch()

local state = lazyrepo._state
assert(state.content_panel == "files")
assert(#vim.api.nvim_tabpage_list_wins(0) == 4)

local files_col = vim.api.nvim_win_get_position(state.panels.files.win)[2]
local branches_col = vim.api.nvim_win_get_position(state.panels.locals.win)[2]
assert(files_col < branches_col)
assert(vim.api.nvim_win_get_position(state.panels.remotes.win)[2] == branches_col)
assert(vim.api.nvim_win_get_position(state.panels.stashes.win)[2] == branches_col)
assert(state.panels.commits.win == nil)

vim.api.nvim_feedkeys("c", "x", false)
assert(state.commit_prompt_win and vim.api.nvim_win_is_valid(state.commit_prompt_win))
assert(vim.api.nvim_get_current_buf() == state.commit_prompt_buf)
vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<CR>", true, false, true), "x", false)
assert(state.message_dialog and vim.api.nvim_win_is_valid(state.message_dialog.win))
assert(vim.api.nvim_win_get_config(state.message_dialog.win).title[1][1] == " Lazyrepo warning ")
vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Esc>", true, false, true), "x", false)
assert(state.message_dialog == nil)
assert(vim.api.nvim_get_current_buf() == state.commit_prompt_buf)
vim.api.nvim_buf_set_lines(state.commit_prompt_buf, 0, -1, false, { "draft message" })
vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Up>", true, false, true), "x", false)
assert(state.commit_history_index == 1)
assert(vim.api.nvim_buf_get_lines(state.commit_prompt_buf, 0, -1, false)[1] ~= "draft message")
vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Down>", true, false, true), "x", false)
assert(state.commit_history_index == 0)
assert(vim.api.nvim_buf_get_lines(state.commit_prompt_buf, 0, -1, false)[1] == "draft message")
vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes("<Esc>", true, false, true), "x", false)
assert(state.commit_prompt_win == nil and state.commit_prompt_buf == nil)

vim.api.nvim_feedkeys("l", "x", false)
assert(state.active == 2)
assert(vim.api.nvim_get_current_buf() == state.panels.locals.buf)

vim.api.nvim_feedkeys("\r", "x", false)
assert(state.content_panel == "commits")
assert(state.active == 5)
assert(state.panels.commits.index == 1)
assert(vim.api.nvim_get_current_buf() == state.panels.commits.buf)
assert(vim.api.nvim_win_get_cursor(state.panels.commits.win)[1] == 1)
assert(vim.api.nvim_win_get_cursor(state.panels.locals.win)[1] == state.panels.locals.index)
assert(#vim.api.nvim_tabpage_list_wins(0) == 4)
assert(state.panels.files.win == nil)
assert(vim.api.nvim_win_get_position(state.panels.locals.win)[2]
  < vim.api.nvim_win_get_position(state.panels.commits.win)[2])

vim.api.nvim_feedkeys("j", "x", false)
local commit = state.panels.commits.items[2]
assert(commit.subject == "initial")
vim.api.nvim_feedkeys("\r", "x", false)
assert(state.commit_files ~= nil)
assert(state.commit_files.oid == commit.oid)
assert(#vim.api.nvim_tabpage_list_wins(0) == 2)
assert(state.panels.locals.win == nil and state.panels.remotes.win == nil and state.panels.stashes.win == nil)
assert(state.panels.files.win == nil)
assert(state.panels.commits.items[2].oid == commit.oid)
assert(state.panels.commits.index == 2)
assert(vim.api.nvim_win_get_position(state.panels.commits.win)[2] == 0)
assert(vim.api.nvim_win_get_position(state.panels.commit_files.win)[2] > 0)
assert(vim.api.nvim_get_current_buf() == state.panels.commit_files.buf)
assert(state.panels.commit_files.items[1].kind == "folder")
assert(state.panels.commit_files.items[2].path == "nested/file.txt")

vim.api.nvim_feedkeys("\r", "x", false)
assert(#state.panels.commit_files.items == 1, "Enter must collapse commit folders")
vim.api.nvim_feedkeys("\r", "x", false)
assert(#state.panels.commit_files.items == 2, "Enter must expand commit folders")
local lazydiff = require("views.lazydiff")
local original_open, opened = lazydiff.open, nil
lazydiff.open = function(opts) opened = opts end
vim.api.nvim_feedkeys("j\r", "x", false)
lazydiff.open = original_open
assert(opened and opened.revision == commit.oid and opened.focus_file == "nested/file.txt")
vim.api.nvim_feedkeys("\t", "x", false)
assert(vim.api.nvim_get_current_buf() == state.panels.commits.buf)
vim.api.nvim_feedkeys("k\r", "x", false)
assert(state.commit_files.subject == "second")
assert(state.panels.commit_files.items[1].path == "second.txt")
assert(vim.api.nvim_get_current_buf() == state.panels.commit_files.buf)
vim.api.nvim_feedkeys("hj\r", "x", false)
assert(state.commit_files.oid == commit.oid)
assert(state.panels.commit_files.items[2].path == "nested/file.txt")
vim.api.nvim_feedkeys("h", "x", false)
vim.api.nvim_feedkeys("\t", "x", false)
assert(vim.api.nvim_get_current_buf() == state.panels.commit_files.buf)

lazyrepo.refresh()
assert(state.commit_files.oid == commit.oid)
assert(state.panels.commits.index == 2)
assert(state.panels.commit_files.items[2].path == "nested/file.txt")
assert(vim.api.nvim_get_current_buf() == state.panels.commit_files.buf)
vim.o.columns = 80
vim.api.nvim_exec_autocmds("VimResized", {})
assert(vim.wait(1000, function() return vim.api.nvim_win_get_width(state.panels.commit_files.win) == 39 end))
assert(#vim.api.nvim_tabpage_list_wins(0) == 2)

vim.api.nvim_feedkeys("\27", "x", false)
assert(state.commit_files == nil)
assert(state.content_panel == "commits")
assert(state.active == 5)
assert(vim.api.nvim_get_current_buf() == state.panels.commits.buf)
assert(state.panels.commits.index == 2)
assert(vim.api.nvim_win_get_cursor(state.panels.commits.win)[1] == 2)
assert(#vim.api.nvim_tabpage_list_wins(0) == 4)
assert(state.panels.commit_files.win == nil)
assert(vim.api.nvim_win_get_position(state.panels.locals.win)[2]
  < vim.api.nvim_win_get_position(state.panels.commits.win)[2])

vim.api.nvim_feedkeys("\27", "x", false)
assert(state.content_panel == "files")
assert(state.active == 2)
assert(vim.api.nvim_get_current_buf() == state.panels.locals.buf)
assert(#vim.api.nvim_tabpage_list_wins(0) == 4)
assert(state.panels.commits.win == nil)
assert(vim.api.nvim_win_get_position(state.panels.files.win)[2]
  < vim.api.nvim_win_get_position(state.panels.locals.win)[2])

vim.o.columns = 80
vim.api.nvim_exec_autocmds("VimResized", {})
assert(vim.wait(1000, function() return #vim.api.nvim_tabpage_list_wins(0) == 4 end))
assert(#vim.api.nvim_tabpage_list_wins(0) == 4)

vim.fn.delete(test_root, "rf")
print("lazyrepo two-column layout tests: ok")
